version: '3'

services:
  frontend:
    command: npm run start
    build:
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  api:
    command: npm run dev
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/nodemon.json:/usr/src/app/nodemon.json
