# PROD # docker-compose up --build
# DEV # docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
# docker exec -it <container_name> sh

version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: realworld-docker-frontend
    command: serve -s dist -l 3000
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: realworld-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com
      - MONGO_URI=mongodb://api_database:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_database

  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - HOST=http://realworld-docker.com
      - MONGO_URI=mongodb://auth_database:27017/auth
    depends_on:
      - auth_database

  api_database:
    image: mongo:latest
    container_name: realworld-docker-api-database
    volumes:
      - mongo_api:/data/db

  auth_database:
    image: mongo:latest
    container_name: realworld-docker-auth-database
    volumes:
      - mongo_auth:/data/dp

  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

volumes:
  mongo_api:
  mongo_auth:
