version: '3'

services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com
      - MONGO_URI=mongodb://api_database:27017/api
    depends_on:
      - api_database

  api_database:
    image: mongo:latest
