# PROD # docker-compose up --build
# DEV # docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build

version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run start
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com
      - MONGO_URI=mongodb://api_database:27017/api
    depends_on:
      - api_database

  api_database:
    image: mongo:latest
    volumes:
      - mongo_api:/data/db

volumes:
  mongo_api:
